version: '3.8'
services:
        db:
                image: postgres:15
                container_name: postgres-miniinventario
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: admin
                        POSTGRES_DB: InventarioMini4BM2
                ports:
                        - "5432:5432"
                restart: always