services:
  - type: web
    name: miniinventario-api
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: miniinventario-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: miniinventario-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: miniinventario-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: miniinventario-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: miniinventario-db
          property: password

databases:
  - name: miniinventario-db
    plan: free