services:
  - type: web
    name: miniinventario-api
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: miniinventario-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: miniinventario-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: miniinventario-db
          property: password

databases:
  - name: miniinventario-db
    plan: free
